### ISSUE TITLE
Example project crashes under lazarus on this line

### ISSUE THREAD

**Issue by laggyluk** [BeRo1985/rnl#2]
Works fine when compiled on lazarus x64 but crashes when compiled in x86 version.
Weird thing is it doesn't happen on my Win10 Home x64 development machine, crashes on remote Win10 Pro x64. CPU: Intel Core Processor (Broadwell) 
https://github.com/BeRo1985/rnl/blob/9e5c6d59679de7cdb43be452f23eec34d111425a/src/RNL.pas#L9911

Figured out I can just jmp through the asm code as this CPU clearly doesn't support this feature. This all happens on a VM btw.

**Comment by BeRo1985** [comment]
Hm, interesting. I think, it's rather a bug of your VM hypervisor instead of RNL itself. Which VM software you do use? So that I can maybe implement a buggy-VM-environment-detection inside RNL. At least, the Intel Core Broadwell Generation itself have definitively support for these rdseed and rdrand instructions. The IvyBridge generation have introduced the rdrand instruction, and the Broadwell generation introduced the rdseed instruction. So I guess, you should better report a bug onto the bugtracker of your VM software. :-)

**Comment by laggyluk** [comment]
Then close it, I have no idea what VM brand it is :P I only have access to operating system running inside VM.
Still curious why it crashes only in x64 build
